### ISSUE TITLE
Update code linting

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#21]
To promote code quality, we can bump up the intensity of the lining rules in the following manner:

- Add `very_good_analysis: ^6.0.0` to the `dev_dependencies:` section of the `pubspec.yaml` file
- Update your `analysis_options.yaml` file as follows:

```
include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    invalid_annotation_target: ignore
    
linter:
  rules:
    public_member_api_docs: false
```

Most linting errors can be fixed by running `dart fix --apply && dart format lib test` then about 10 errors will need manual fixes. This should be done though once you are finished with everything else. If you feel it can't go into this PR, I can convert this into an issue to enhance code quality.

_Originally posted by @MillerAdulu in https://github.com/droidconKE/flutterconKEApp/issues/19#issuecomment-2251478269_
